version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/instagram-analyzer-dev
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
      - temp_instagram_data_dev:/app/temp_instagram_data

  mongo:
    image: mongo:6
    ports:
      - "27018:27017"
    volumes:
      - mongo_data_dev:/data/db
    environment:
      - MONGO_INITDB_DATABASE=instagram-analyzer-dev

volumes:
  mongo_data_dev:
  temp_instagram_data_dev:
