version: "3.8"

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/instagram-analyzer
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - temp_instagram_data:/app/temp_instagram_data

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=instagram-analyzer

volumes:
  mongo_data:
  temp_instagram_data:
